# Generated by Django 5.2.7 on 2025-10-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
    ]
